title = "Sjj's BLOG"
theme = "PaperMod"
languageCode = "en-us"
baseURL = "https://sjjaugust.github.io/"
copyright = "shijunjie © {year}"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.mermaid]
    options={theme="default"}

[socialIcons]
  name = "rss"
  url = "https://sjjaugust.github.io/index.xml"


[params]
  defaultTheme = "auto"
  ShowShareButtons = false 
  ShareButtons = ["rss"]
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  Comments = false
  [params.homeInfoParams]
    Title = "Hi there!"  
    Content = "行吧"
  [[param.socialIcons]]
    name = "Github"
    url = "https://github.com/sjjaugust"
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]
  [params.editPost]
    URL = "https://github.com/sjjaugust/SjjAugust.github.io/tree/main/content"
    Text = "Suggest Changes"
    appendFilePath = true


# Navigation
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "所有文章"
    url = "/archives"
    weight = 1

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search"
    weight = 2
   
  
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags"
    weight = 4
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/sjjaugust"
    weight = 5
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "https://sjjaugust.github.io/index.xml"
    weight = 6
